version: '3'

services:
  upload_img:
    image: flask-file-upload-app
    ports:
      - "8089:8089"
    volumes:
      - ./:/app/
    environment:
      #- FLASK_ENV=development
      - API_HOST=http://localhost
      - API_PORT=8089